/**
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 * http://www.dspace.org/license/
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.18 at 07:02:06 PM CEST 
//


package org.dspace.ref.compliance.definition.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the test.xjc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RuleCategories_QNAME = new QName("", "rule-categories");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: test.xjc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CategorySet }
     * 
     */
    public CategorySet createCategorySet() {
        return new CategorySet();
    }

    /**
     * Create an instance of {@link RuleDefinition }
     * 
     */
    public RuleDefinition createRuleDefinition() {
        return new RuleDefinition();
    }

    /**
     * Create an instance of {@link RuleCategory }
     * 
     */
    public RuleCategory createRuleCategory() {
        return new RuleCategory();
    }

    /**
     * Create an instance of {@link RuleSet }
     * 
     */
    public RuleSet createRuleSet() {
        return new RuleSet();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CategorySet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rule-categories")
    public JAXBElement<CategorySet> createRuleCategories(CategorySet value) {
        return new JAXBElement<CategorySet>(_RuleCategories_QNAME, CategorySet.class, null, value);
    }

}
